commands:
  localize:
    desc: Resolve local package dependencies for fast development
    args: []

  publish:
    desc: Fix all resolved local dependencies, commit changes to github, publish all packages on npm
    args: []

options:
  debug:
    short: d
    desc: output extra debugging
  small:
    short: s
    desc: small pizza size
  pizza-type:
    short: p
    desc: flavour of pizza
    arg: type
